baseURL = 'https://breastfeeding.scot'
languageCode = 'en-gb'
title = 'Breastfeeding support in Scotland'
disableKinds = ["taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject = true
enableGitInfo = true
[goldmark.renderer]
unsafe = true
